version: '3.8'

services:
  backend:
    container_name: backend
    build: backend
    ports:
      - "8080:8080"
    networks:
      - geoserver-net

  postgres:
    image: postgis/postgis:13-3.1
    container_name: gis_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geoserver-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: gis_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - geoserver-net

networks:
  geoserver-net:
    driver: bridge

volumes:
  postgres_data: