version: '3.8'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: gis_postgres
    ports:
      - "${POSTGIS_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - geoserver-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: gis_pgadmin
    ports:
      - "${PGADMIN_PORT}:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - geoserver-net

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.1
    container_name: geoserver_GIS
    ports:
      - "${GEOSERVER_PORT}:8080"
    environment:
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - geoserver-net

  certbot: # certbot 서비스 추가
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"
    networks:
      - geoserver-net

  backend:
    container_name: backend
    image: ${DOCKER_USERNAME}/${REPO_NAME}-backend:${VERSION}
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGIS_PORT: ${POSTGIS_PORT}
      VWORLD_KEY: ${VWORLD_KEY}
      FRCN_RENT_INFO_KEY: ${FRCN_RENT_INFO_KEY}
      DOMAIN: ${DOMAIN}
    networks:
      - geoserver-net
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: ${DOCKER_USERNAME}/${REPO_NAME}-frontend:${VERSION}
    ports:
      - "${FRONTEND_PORT}:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      VITE_GEOSERVER_URL: ${VITE_GEOSERVER_URL}
      VITE_PGADMIN_URL: ${VITE_PGADMIN_URL}
      VITE_DOMAIN: ${VITE_DOMAIN}
      TZ: Asia/Seoul
    volumes:
      - ssl:/etc/letsencrypt/live/${DOMAIN}
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    networks:
      - geoserver-net

networks:
  geoserver-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
  ssl:
