spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGIS_PORT}/${POSTGRES_DB}?ssl=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        id:
          new_generator_mappings: true
    show-sql: true
  batch:
    job:
      enabled: false

api:
  vworld:
    key: ${VWORLD_KEY}
  frcn-rent-info:
    key: ${FRCN_RENT_INFO_KEY}

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api-docs

domain: ${DOMAIN}
